Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: certifi in /home/ubuntu/.local/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (2024.8.30)
Requirement already satisfied: telethon in /home/ubuntu/.local/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (1.37.0)
Requirement already satisfied: pymongo in /home/ubuntu/.local/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (4.10.1)
Requirement already satisfied: pyaes in /home/ubuntu/.local/lib/python3.11/site-packages (from telethon->-r requirements.txt (line 2)) (1.6.1)
Requirement already satisfied: rsa in /home/ubuntu/.local/lib/python3.11/site-packages (from telethon->-r requirements.txt (line 2)) (4.9)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /home/ubuntu/.local/lib/python3.11/site-packages (from pymongo->-r requirements.txt (line 3)) (2.7.0)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python3/dist-packages (from rsa->telethon->-r requirements.txt (line 2)) (0.4.8)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: certifi in /home/ubuntu/.local/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (2024.8.30)
Requirement already satisfied: telethon in /home/ubuntu/.local/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (1.37.0)
Requirement already satisfied: pymongo in /home/ubuntu/.local/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (4.10.1)
Requirement already satisfied: pyaes in /home/ubuntu/.local/lib/python3.11/site-packages (from telethon->-r requirements.txt (line 2)) (1.6.1)
Requirement already satisfied: rsa in /home/ubuntu/.local/lib/python3.11/site-packages (from telethon->-r requirements.txt (line 2)) (4.9)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /home/ubuntu/.local/lib/python3.11/site-packages (from pymongo->-r requirements.txt (line 3)) (2.7.0)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python3/dist-packages (from rsa->telethon->-r requirements.txt (line 2)) (0.4.8)
Starting zipper.py...
